-- MySQL Script generated by MySQL Workbench
-- 07/08/16 08:56:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm` DEFAULT CHARACTER SET utf8 ;
USE `crm` ;

-- -----------------------------------------------------
-- Table `crm`.`t_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`t_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rolename` VARCHAR(45) NULL COMMENT '角色名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`t_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL COMMENT '账号',
  `password` VARCHAR(100) NULL COMMENT '密码（加密）',
  `realname` VARCHAR(45) NULL COMMENT '员工姓名',
  `weixin` VARCHAR(45) NULL COMMENT '用户的微信ID',
  `createtime` TIMESTAMP NULL DEFAULT current_timestamp COMMENT '用户的创建时间',
  `roleid` INT NOT NULL COMMENT '角色ID',
  PRIMARY KEY (`id`),
  INDEX `fk_t_user_t_role1_idx` (`roleid` ASC),
  CONSTRAINT `fk_t_user_t_role1`
    FOREIGN KEY (`roleid`)
    REFERENCES `crm`.`t_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`t_user_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`t_user_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logintime` VARCHAR(45) NULL COMMENT '登录时间',
  `loginip` VARCHAR(45) NULL COMMENT '登录ip',
  `userid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_user_log_t_user_idx` (`userid` ASC),
  CONSTRAINT `fk_t_user_log_t_user`
    FOREIGN KEY (`userid`)
    REFERENCES `crm`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
